name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: |
        cd packages/backend
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd packages/backend
        source venv/bin/activate
        echo "No tests defined yet"
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Install Frontend Dependencies
      run: |
        cd packages/frontend
        npm install
    - name: Build Frontend
      run: |
        cd packages/frontend
        npm run build 
